<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Audit.Application\Audit.Application.csproj" />
    <ProjectReference Include="..\Audit.Domain\Audit.Domain.csproj" />
    <ProjectReference Include="..\..\..\Core\ATSolution.Application\ATSolution.Application.csproj" />
    <ProjectReference Include="..\..\..\Core\ATSolution.Infrastructure\ATSolution.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\SharedKernel\ATSolution.SharedKernel\ATSolution.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SeedData\**\*.json">
      <LogicalName>SeedData.%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
