version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped

    ports:
      - "80:80"
      # Uncomment if using HTTPS later
      # - "443:443"

    volumes:
      - /volume1/docker/nginx/conf.d:/etc/nginx/conf.d
      - /volume1/docker/nginx/logs:/var/log/nginx

    networks:
      - avikans

networks:
  avikans:
    external: true